<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<section xmlns="http://docbook.org/ns/docbook" version="5.0" xmlns:xlink="http://www.w3.org/1999/xlink" xml:id="_PythonException_8H">
<title>include/jevois/Debug/PythonException.H File Reference</title>
<indexterm><primary>include/jevois/Debug/PythonException.H</primary></indexterm>
<programlisting>#include &lt;string&gt;
#include &lt;boost/python/errors.hpp&gt;
#include &lt;boost/python/object.hpp&gt;
</programlisting>Include dependency graph for PythonException.H:<para>
    <informalfigure>
        <mediaobject>
            <imageobject>
                <imagedata width="50%" align="center" valign="middle" scalefit="0" fileref="PythonException_8H__incl.png"></imagedata>
            </imageobject>
        </mediaobject>
    </informalfigure>
</para>
This graph shows which files directly or indirectly include this file:<para>
    <informalfigure>
        <mediaobject>
            <imageobject>
                <imagedata width="50%" align="center" valign="middle" scalefit="0" fileref="PythonException_8H__dep__incl.png"></imagedata>
            </imageobject>
        </mediaobject>
    </informalfigure>
</para>
<simplesect>
    <title>Namespaces    </title>
        <itemizedlist>
            <listitem><para> <link linkend="_namespacejevois">jevois</link></para>

<para>所有 JeVois 类和函数的主命名空间 </para>
</listitem>
        </itemizedlist>
</simplesect>
<simplesect>
    <title>Functions    </title>
        <itemizedlist>
            <listitem><para>std::string <link linkend="_group__debugging_1gaede3301d7e76cf562b3c9326b7b3d686">jevois::getPythonExceptionString</link> (boost::python::error_already_set &amp;)</para>

<para>Python 异常转换为字符串，以便我们可以将回溯打印到我们的 serlog stream. </para>
</listitem>
        </itemizedlist>
</simplesect>
</section>
